id: I61133207
legacy_id: P010676
ocr_import_info:
  bdrc_scan_id: W23926
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T06:00:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:16:54.935223+00:00'
last_modified: 2022-09-02 13:17:43.649546
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23926
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23926
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐེག་པ་ཐམས་ཅད་ཀྱི་ཤན་འབྱེད་ཉི་འོད་རབ་གསལ།
  author: ཀཿ་ཐོག་པ་བསོད་ནམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8635962494746414
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I3566:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3566
      total_pages: 464
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3566.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8691961144990382
    legacy_id: v001
  I3567:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3567
      total_pages: 366
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3567.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8567239915375139
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
